networks:
  api_database_network:
    driver: bridge
  web_api_network:
    driver: bridge

volumes:
  db_data_volume:

services:
  database_service:
    image: postgres:18
    container_name: database_service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data_volume:/var/lib/postgresql
    networks:
      - api_database_network

  api_service:
    build: ./spring-api
    container_name: api_service
    restart: unless-stopped
    depends_on:
      - database_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database_service:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - api_database_network
      - web_api_network

  web_service:
    build: 
      context: ./webapp
      args:
        VITE_API_BASE_URL: http://localhost:81
    container_name: web_service
    restart: unless-stopped
    networks:
      - web_api_network

  reverse_proxy_service:
    image: nginx:1.29-alpine
    container_name: reverse_proxy_service
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web_service
      - api_service
    networks:
      - web_api_network