networks:
  api_database_network:
    driver: bridge
  reverse_proxy_network:
    driver: bridge
  pgadmin_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:

services:
  db:
    image: postgres:18
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - api_database_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_SETUP_USER: ${PGADMIN_EMAIL}
      PGADMIN_SETUP_PASSWORD: ${PGADMIN_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - reverse_proxy_network
      - pgadmin_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://pgadmin:80"]
      interval: 15s
      timeout: 3s
      retries: 5

  spring-api:
    build: ./spring-api
    container_name: spring-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - api_database_network
      - reverse_proxy_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://spring-api:8080/api/health"]
      interval: 15s
      timeout: 3s
      retries: 5

  webapp:
    build:
      context: ./webapp
      args:
        VITE_API_BASE_URL: http://localhost:80
    container_name: webapp
    restart: unless-stopped
    networks:
      - reverse_proxy_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://webapp:80"]
      interval: 15s
      timeout: 3s
      retries: 5

  reverse-proxy:
    image: nginx:1.29-alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      webapp:
        condition: service_healthy
      spring-api:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
    networks:
      - reverse_proxy_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://reverse-proxy:80"]
      interval: 10s
      timeout: 3s
      retries: 5
