services:

  db:
    environment:
      POSTGRES_LOG_STATEMENT: all
    ports:
      - "5432:5432"
    healthcheck:
      disable: true

  spring-api:
    build:
      context: ./spring-api
      target: dev
    volumes:
      - ./spring-api/src:/app/src
      - ~/.m2:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev
    command: ["mvn", "spring-boot:run"]
    ports:
      - "8080:8080"
    healthcheck:
      disable: true
    depends_on:
      - db

  webapp:
    build:
      context: ./webapp
      target: dev
    command: ["npm", "run", "dev"]
    volumes:
      - ./webapp:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:80
    healthcheck:
      disable: true

  reverse-proxy:
    volumes:
      - ./reverse-proxy/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 0
    ports:
      - "80:80"
    healthcheck:
      disable: true
    depends_on:
      - spring-api
      - webapp
